CREATE TABLE t_departments
(
    id   int4 GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255),
    PRIMARY KEY (id)
);
CREATE TABLE t_departments_child_departments
(
    department_id        int4 NOT NULL,
    child_departments_id int4 NOT NULL
);
CREATE TABLE t_departments_users
(
    department_id int4 NOT NULL,
    users_id      int4 NOT NULL
);
CREATE TABLE t_users
(
    id            int4 GENERATED BY DEFAULT AS IDENTITY,
    age           int4,
    name          varchar(255),
    phone_number  varchar(255),
    department_id int4,
    PRIMARY KEY (id)
);
ALTER TABLE if EXISTS t_departments_child_departments ADD CONSTRAINT UK_q08w44g35jw51u7gw9lew24fm UNIQUE (child_departments_id);
ALTER TABLE if EXISTS t_departments_users ADD CONSTRAINT UK_rh9cu3c4oojh99olc90jr54ce UNIQUE (users_id);
ALTER TABLE if EXISTS t_departments_child_departments ADD CONSTRAINT FKrmrtfgvbk1ldvm9r50ysi845n FOREIGN KEY (child_departments_id) REFERENCES t_departments;
ALTER TABLE if EXISTS t_departments_child_departments ADD CONSTRAINT FKm51j4rxrd7io4nptnt1edjrjm FOREIGN KEY (department_id) REFERENCES t_departments;
ALTER TABLE if EXISTS t_departments_users ADD CONSTRAINT FK74uliuh6v583597jlsxp68a41 FOREIGN KEY (users_id) REFERENCES t_users;
ALTER TABLE if EXISTS t_departments_users ADD CONSTRAINT FKpsckqurfocl1r76m5r3o6mhks FOREIGN KEY (department_id) REFERENCES t_departments;
ALTER TABLE if EXISTS t_users ADD CONSTRAINT FK6rmluaq2cbbxwmgxlcqb6ugik FOREIGN KEY (department_id) REFERENCES t_departments;